### ISSUE TITLE
Get popular assets server side

### ISSUE THREAD

**Issue by aronhoyer** [equinor/data-marketplace#198]
**In order to improve the experience for the end user, we will get popular assets server side**

## Acceptance
- Popular assets are loaded server side to avoid loading spinners and content jump (CLS)

**Comment by wenche** [comment]
We have tested this a bit, but we found the performance to be unacceptable probably because of the recursive calls to Colibra to fetch the 6 most popular assets. A potential future enhancement can rather be to use incremental static rendering for the frontpage.

Mobile vs desktop

![Image](https://user-images.githubusercontent.com/1568252/187179639-43fae4d8-b59f-40b3-a06b-4fac1eafbe2a.png)

![Image](https://user-images.githubusercontent.com/1568252/187179659-b11811a2-17d4-4f59-91e4-af541b418a01.png)
